### ISSUE TITLE
md-card: insertBefore error with ng-if and child state

### ISSUE THREAD

**Issue by epelc** [angular/material#1402]
`md-card` is throwing the following error if you have an `ng-if` on it and you navigate to a child state. It works fine if you switch to `ng-show`. Also you don't get the error if you just toggle whatever value your `ng-if` is checking. It only seems to throw it when you go to a child state.

Error
```
"TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:3165:13)
    at Object.JQLite.(anonymous function) [as after] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:3249:17)
    at Object.$AnimateProvider.$get.enter (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:4668:23)
    at Object.angular.module.directive.factory.config.$provide.decorator.enter (http://dev.mysite.com/app/bundle.js:27684:22)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:21911:26
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:6953:29)
    at $get.boundTranscludeFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:7093:16)
    at controllersBoundTransclude (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:7749:18)
    at Object.ngIfWatchAction [as fn] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:21902:15)
    at Scope.$get.Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.js:14226:29)"
```
Example markup
```
<md-button ui-sref="thisState.someChildState">go to child</md-button>
<md-card layout="column" layout-align="center" ng-if="someVar">
    <md-card-content>
        <h3>Admin</h3>
        <p>Clicking the go to child button will throw an error due to the ng-if</p>
    </md-card-content>
</md-card>
```

**Comment by matsko** [comment]
Could you please try using 1.4.6? We fixed various issues with ngShow and ngIf working together.

**Comment by ThomasBurleson** [comment]
Please test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).
Can you confirm the issue still exists with the above versions ?

**Comment by jacksonrayhamilton** [comment]
I am having the same issue with `ngIf` inside `mdSubheader`. After hopping through the debugger, I think at some point a `comment` node generated for an `ngIf` gets passed to jqLite's `after` method.

Here's a reproduction:

`bower.json`:

```json
{
  "name": "dialog-bug",
  "dependencies": {
    "angular": "~1.4.6",
    "angular-material": "~0.11.0"
  }
}
```

`index.html`:

```html
<html ng-app="app">
    <head>
        <link rel="stylesheet" href="bower_components/angular-material/angular-material.css">
    </head>
    <body>
        <md-subheader>
            <span ng-if="true">Hello World</span>
        </md-subheader>
        <script src="bower_components/angular/angular.js"></script>
        <script src="bower_components/angular-animate/angular-animate.js"></script>
        <script src="bower_components/angular-aria/angular-aria.js"></script>
        <script src="bower_components/angular-material/angular-material.js"></script>
        <script>angular.module('app', ['ngMaterial']);</script>
    </body>
</html>
```

Produces:

```
TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (bower_components/angular/angular.js:3451:13)
    at Object.JQLite.(anonymous function) [as after] (bower_components/angular/angular.js:3535:17)
    at domInsert (bower_components/angular/angular.js:5048:35)
    at Object.$provide.$get.afterElement.enter (bower_components/angular/angular.js:5211:9)
    at bower_components/angular/angular.js:24003:26
    at publicLinkFn (bower_components/angular/angular.js:7545:29)
    at name.$get.boundTranscludeFn (bower_components/angular/angular.js:7690:16)
    at controllersBoundTransclude (bower_components/angular/angular.js:8307:18)
    at Object.ngIfWatchAction (bower_components/angular/angular.js:23994:15)
    at Object.constantListener [as fn] (bower_components/angular/angular.js:14320:20)
```

**Comment by topherfangio** [comment]
@jacksonrayhamilton I believe the subheader issue was fixed in a semi-recent release as I cannot reproduce it anymore (and I remember writing code to fix it).

@epelc Do you know if this is still an issue? If so, is there any chance you could provide a Codepen which actually demonstrates it so that we can track it down?

Thanks!

**Comment by epelc** [comment]
@topherfangio it still happens in 0.11.2 and also in the latest master

Here is a [demo](http://codepen.io/anon/pen/RWYNXZ?editors=101). The second button takes you to a child state which triggers the error. The work around for the error is surrounding the `md-card` in a `div` or any other element.

**Comment by topherfangio** [comment]
Thanks @epelc ! We'll take a look and try to get it in the next release.

**Comment by felixbanguera** [comment]
So, I'm on AngularJS v1.7.8 (it's still angular js cause I'm working with Node-Red, just in case someone asks), this issue is happening and it doesn't even show an error in node-red, but I enclosed the `md-card` with a `div` and it worked. So, was this never fixed?

**Comment by Splaktar** [comment]
@felixbanguera it was closed as deprecated a couple of years ago.

I took the CodePen above and [updated it](https://codepen.io/Splaktar/pen/arLYbg?editors=101) and this issue appears to have gone away with that configuration. You don't mention what version of AngularJS Material you are using, but `1.1.18` is what is used in the updated CodePen.

**Comment by felixbanguera** [comment]
@Splaktar I tried the code pen and it still happen.

if you remove the div that enclose the md-card the ng-if stops working...
remove `<div ui-view layout-margin>`   and the closing `</div` tag and it will happen.

I'm using Angularjs-material 1.1.18 which is the same used in the codepen.

**Comment by Splaktar** [comment]
@felixbanguera I updated the [CodePen](https://codepen.io/Splaktar/pen/arLYbg?editors=101) to comment out those lines and I still don't see the exception on Chrome. Can you fork the CodePen and post a broken example?

**Comment by felixbanguera** [comment]
@Splaktar Yeah, probably I wasn't totally clear. I'm not talking about the exception, it's that the ng-if directive seems not to work: when surrounded by divs the md-card gets removed and showed when clicking the buttons, but when the divs are removed, the md-card just remains there, it doen's get removed when changing the ng-if validation through the buttons.

**Comment by Splaktar** [comment]
@felixbanguera that appears to be an issue with ui-router or the configuration of [this CodePen example](https://codepen.io/Splaktar/pen/arLYbg?editors=1010). The value of `someBool` isn't being changed, so the `ng-if` doesn't do anything since the value remains `true`. I haven't used ui-router much lately, so it's not clear to me why there were two `ui-view` attributes.
