### ISSUE TITLE
mdSelect causes page to jump to top when clicked

### ISSUE THREAD

**Issue by dozingcat** [angular/material#1648]
See http://codepen.io/anon/pen/LEmgvE . Scroll down a bit, click the mdSelect to open it, and the page will scroll back to the top.

**Comment by ilanbiala** [comment]
I have this issue as well.

**Comment by chr22** [comment]
This is still an issue as of 0.8.3, but only in Firefox

**Comment by Oskar-Andersson** [comment]
I have this same issue, and I believe its because the page somehow ignores "scrollTop", i.e. the displacement of the displayed option-list is related to the amount scolled from document top. I would try to fix this myself if I had the time, sadly I do not. Hopefully someone else can fix it fairly quickly, since its a rather severe and UX breaking bug for (as someoene else wrote) FF users!

**Comment by Novashock** [comment]
This is still happening for me, has anyone tested out the 0.8.3 version and notice this has been resolved?

**Comment by Oskar-Andersson** [comment]
As chr22 wrote, yes it is still in 0.8.3 but apparently only in FF (which is what I use).

**Comment by ilanbiala** [comment]
I actually have this issue on Chrome and it's been present for a few Chrome versions and a few ngMaterial versions.

**Comment by Novashock** [comment]
Thanks @Oskar-Andersson and @ilanbiala nope to find a way around this.

**Comment by jl4282** [comment]
I'm using 0.8.3 and this is still an issue in Chrome 41.0.2272.89 (64-bit)

**Comment by ilanbiala** [comment]
Big bug that prevents mdSelect from really being usable. @ThomasBurleson @rschmukler @ajoslin any ideas what's going on?

**Comment by atsuya** [comment]
Same here with 0.8.3.

**Comment by mrmarktyy** [comment]
Same here ;(

**Comment by atsuya** [comment]
i confirmed it's been fixed for me :cat: :zap:
thanks!

**Comment by moeduffdude** [comment]
i've tested it on Safari, Chrome and Firefox (all latest releases) and it's working like a charm

@rschmukler thank you for all the work

**Comment by alifarahani** [comment]
Sorry Guys I've been having the same issue, should I wait for the next update?

Thanks

**Comment by Novashock** [comment]
I am here with you on that @alifarahani I think we should just wait!

**Comment by alifarahani** [comment]
Thanks @Novashock  ! ! !

**Comment by rschmukler** [comment]
@Novashock / @alifarahani are you running off of master or 0.8.3? It should be fixed, even though it hasn't been released yet.

**Comment by alifarahani** [comment]
@rschmukler I updated to 0.8.3 but is not fixed . . .

**Comment by rschmukler** [comment]
@alifarahani Yeah it was still in 0.8.3. But it will be fixed when we release next.

**Comment by alifarahani** [comment]
@rschmukler Thanks man keep up the good work ! ! !

**Comment by davecas** [comment]
i have the same issue with the 0.8.3 version. when this issue was settled?

**Comment by demisx** [comment]
Shall the milestone be updated for this issue? Obviously, this bug is still in 0.8.3.

**Comment by butaixianran** [comment]
Why close this issue??? It hasn't been fixed yet! Even in 0.9.4
check this:
http://codepen.io/butaixianran/pen/waWRmN

This issue is still in firefox  38+

**Comment by patouche7519** [comment]
it's strange but this code works with firefox.
<div ng-app="demoApp" 
     ng-controller="DemoController">
<md-content style="height: 900px;">
      <div style="height: 300px; background: lightblue;"></div>
      Favorite color:
      <md-select ng-model="selectedColor">
        <md-option ng-repeat="c in colors" ng-value="c">{{c}}</md-option>
      </md-select>
      You have selected {{selectedColor}}
      <div style="height: 600px; background: lightgreen;"></div>
      <md-select ng-model="selectedColor">
        <md-option ng-repeat="c in colors" ng-value="c">{{c}}</md-option>
      </md-select>
</md-content>
</div>

 I had the same issue on Chrome with a md-select in form (yesterday with the #master version). And it works for me too. Fixed height in a md-content tag. It's not "the" solution but you can go on until the great team fixe the issue ;).

**Comment by vs4vijay** [comment]
Its not even fixed in 0.10.0 version, Firefox has same issue but working in chrome.

**Comment by dozingcat** [comment]
The codepen demo is now working for me in Firefox, but my actual app still has the incorrect behavior. I'll try to create another reproduction.

**Comment by vs4vijay** [comment]
@dozingcat any update on this? Have you overcome this problem?

**Comment by g2graman** [comment]
Issue still present for Chrome version 43.0.2357.134 (64-bit)

**Comment by alarrosa14** [comment]
Happens to me with mdAutocomplete in Firefox.

**Comment by alarrosa14** [comment]
Just to record that 0.10.1-rc3 fixed the issue for me.

**Comment by pjbull** [comment]
If anyone needs a CSS workaround, this worked for me:

    .md-select-label {
        padding-bottom: 2px !important;
        border-width: 1px !important;
    }

**Comment by stevenmwade** [comment]
Still happening to me in 1.0.2.

**Comment by jayeshanandani** [comment]
md-select still is resulting in jump of page in 1.0.2. Can reproduce.

**Comment by jsantana90** [comment]
Mine jumps to top and even makes the screen completely blank angular:angular-material@1.0.1

**Comment by j-slvr** [comment]
for me md-select is virtually unusable below the fold because of this (1.0.2)

**Comment by ajagnanan** [comment]
So this is still happening for me. Not sure whats wrong, but it seems that styles are being placed on the body tag, the culprit being "top" set to -x value. This provides a workaround for now:

```
// Save mouse positions so we have them globally
$(document).mousemove(function(e) {
    window.x = e.pageX;
    window.y = e.pageY;
});

// Function needs to be placed on the md-select "md-on-open"
$rootScope.fixPosition = function(){
            $timeout(function(){
                $('body').removeAttr('style');
                if (document.getElementsByClassName('md-active')) {
                    for (var i = 0; i < document.getElementsByClassName('md-active').length; i++) {
                        var ele = document.getElementsByClassName('md-active')[i];
                        if (ele.localName == 'div') {
                            var position = y - ele.clientHeight;
                            ele.style.top = position + "px";
                        }
                    }
                }
            }, 10);
        };
```

**Comment by blankazucenalg** [comment]
Version 1.1.4 still causes this even with Chrome.
Version 1.1.1 works fine with both Chrome and Firefox

**Comment by cesardmoro** [comment]
having the same issue

**Comment by gvorster** [comment]
In FF 57.0 I can see an md-select inside a dialog, but cannot close it with clicking outside the select box.

**Comment by shwethachavdi** [comment]
body {
    position: initial !important;
    top: initial !important;
    overflow: initial !important;
}
html {
    overflow: initial !important;
}
 worked for me.

**Comment by Splaktar** [comment]
If you are still seeing this or a similar issue, please open a new issue with a CodePen reproduction.
