### ISSUE TITLE
A vertical scrollbar appeared on inputs with icon with no padding-bottom

### ISSUE THREAD

**Issue by jgoux** [angular/material#2609]
Hi,
since the last release, a vertical scrollbar appeared on inputs with icon when the input-container has no padding-bottom.
Example : http://codepen.io/jgx/pen/mJyZoZ
Usually, this is useful when the input is alone in its container or is the last one.

**Comment by robertbaker** [comment]
Your pen doesn't display the scrollbar. However I have the same issue.

I fixed it by doing padding-bottom:4px on the input-container.

**Comment by ThomasBurleson** [comment]
Does this Commit SHA f1df6dc09c20635d42ffaada32ae2f036666a5ba not fix this now?

**Comment by jgoux** [comment]
@ThomasBurleson According to the codepen, it seems good now :+1:

**Comment by jgoux** [comment]
Sorry I didn't see @robertbaker 's answer, I reopen the issue waiting for his feedback.

**Comment by ThomasBurleson** [comment]
@jgoux - I will close for now. Can reopen if problem persists.

**Comment by robertbaker** [comment]
It is fixed for me. However the icon isn't vertically centered in an md-toolbar
![capture](https://cloud.githubusercontent.com/assets/907301/7423812/6cf5d6ac-ef4e-11e4-9400-45aa737883c9.PNG)

**Comment by ThomasBurleson** [comment]
@robertbaker - do you have quick demo that we can use to easily test and iterate a good fix?
