### ISSUE TITLE
md-autocomplete: $scope.textChange is not a function

### ISSUE THREAD

**Issue by norkunas** [angular/material#3388]
I use ```md-chips``` with ```md-autocomplete``` and I get this error.
Codepen http://codepen.io/anon/pen/warZPb
Angular 1.4.1 and Angular material 0.10.0

Code in codepen is only partial but it reproduces this error.

Also i don't understand why the second input get's the focus if i don't use ```md-autofocus```.
And when clicking outside the chips container it still has focus.

If this because of main error?

**Comment by gkalpak** [comment]
This is due to a recent change in Angular and has been fixed with 62f5c7b. [Working on latest build][1]
In the mean-time, you could work-around the issue by specifying `md-search-text-change="null"` on your autocomplete.

[1]: http://codepen.io/ExpertSystem/pen/vOewYP

**Comment by norkunas** [comment]
@gkalpak thanks. Additionaly maybe do you know something about my other questions?

**Comment by gkalpak** [comment]
@norkunas, nope :)

**Comment by 09star** [comment]
@gkalpak  hi , I use md-contact-chips  , come up with the same error.  I put md-search-text-change="null" in the  md-contact-chips directive while the error still exist . Did I do something wrong ? any help ? thank you.

**Comment by gkalpak** [comment]
@09star, could you provide a live demo (e.g. using CodePen) ?

**Comment by 09star** [comment]
@gkalpak    I changed the demo from [Anuglar Material](https://material.angularjs.org/latest/#/demo/material.components.chips) 
just change the angular and angular animate version to 1.4.1 , then open developer tools of broswer __the $scope.textChange is not a function__ error exist .  [codepen demo here](http://codepen.io/anon/pen/QbmYaX)   :)

**Comment by gkalpak** [comment]
@09star, I can't reproduce the error with your demo.
Can you provide a demo that reproduces the error (i.e. it has `md-search-text-change="null"` and still the error is logged in the console) ?

**Comment by boneskull** [comment]
:+1:

**Comment by hitigon** [comment]
found the same error under Angular 1.4.2

**Comment by robinsving** [comment]
@gkalpak, the demo that @09star provided had no md-autocomplete. Where are you adding the <code>md-search-text-change="null"</code> to make his demo work?

Also, I have the same problem with Angular 1.4.2, so +1

**Comment by norkunas** [comment]
@robinsving md-contact-chips uses autocomplete internally, if you want to workaround this, use decorator to override default template and add these manually ```md-selected-item-change="null" md-search-text-change="null"```

**Comment by robinsving** [comment]
@norkunas That should suffice as a workaround for now. Thank you

**Comment by sukyumKim** [comment]
@gkalpak thanks for comment!!

**Comment by robertmesserle** [comment]
This is resolved in 0.10.1-rc1
