### ISSUE TITLE
Material tabs behave differently with the latest angular 1.4.1

### ISSUE THREAD

**Issue by navneet35371** [angular/material#3434]
I am trying to create simple angular material tabs using latest angular release. But i am not getting the expected behavior of tabs.

Example - using angular v1.4.1

    http://codepen.io/navneet35371/pen/QbOqWy

Example using angular v1.3.15

    http://codepen.io/clairebones/pen/EjNeWY

You could see the animation using the latest version is not quite smooth. It looks like tabs are reloaded after animation.

**Comment by ricardobfa** [comment]
+1

**Comment by Davidonium** [comment]
I'm having this problem too

**Comment by JanPrinsloo** [comment]
Same here

**Comment by amritk** [comment]
+ 1

**Comment by salalaslam** [comment]
+1

**Comment by JSlifierz** [comment]
+1

I reverted back to angular 1.4.0 and the animation is smooth again. However, remember to include ```md-dynamic-height``` in the md-tabs tag if your content requires a height > 250px

**Comment by petesharum** [comment]
I'm also having this problem. Reverting to angular 1.4.0 fixes it for now.

**Comment by loveapoex** [comment]
+1

**Comment by Z3V0K0D3** [comment]
using angular v1.4.1 tab align center, in angular v1.3.15 align left ok

**Comment by robertmesserle** [comment]
This issue is being resolved in Angular 1.4.2 - it is being tracked in a separate issue.

**Comment by petesharum** [comment]
@robertmesserle Could you please reference the other issue?

**Comment by robertmesserle** [comment]
@petesharum looking now, I got a somewhat massive influx of issues today that I am sorting through. =p

**Comment by robertmesserle** [comment]
Actually, after looking at the other issue, I'm going to use this one to track.

The other issue I recalled seeing: https://github.com/angular/material/issues/3353

And a related issue from Autocomplete: https://github.com/angular/material/issues/3388

**Comment by salalaslam** [comment]
angular 1.4.2 doesn't solve the problem
http://codepen.io/salalaslam/pen/RPxVqX

**Comment by bruno-fernandes** [comment]
Having the same issue with 1.4.2

**Comment by robertmesserle** [comment]
@bruno-fernandes @salalaslam This was an issue in 0.10.0 and is already fixed in master (which will be in the 0.10.1 release).  I went ahead and addressed another issue I found while debugging this one as well (where initial styles were not being set for the inkbar when using centered tabs).  Closing.

**Comment by Z3V0K0D3** [comment]
same issue with 1.4.2

**Comment by ThomasBurleson** [comment]
@salalaslam, @bruno-fernandes, @Z3V0K0D3 - can you confirm this is resolved with v0.10.1-rc1 (latest in master).

**Comment by salalaslam** [comment]
yes it is solved in latest angular-material v0.10.1-rc1 with angularjs v1.4.2
http://codepen.io/salalaslam/pen/eNMoMX
