### ISSUE TITLE
md-autocomplete jumps to top on IE11.

### ISSUE THREAD

**Issue by deckikwok** [angular/material#3511]
using IE 11 edge. on selection of a choice in autocomplete, scrolls jumps to the top. verified it to be working properly on 0.10.0 for Chrome but not on IE11.

**Comment by Splaktar** [comment]
@deckikwok Do you have a CodePen for this? It's not clear to me by your description what the problem is. I've tried to reproduce but everything seems to be behaving.

**Comment by eloyleonardo** [comment]
I have the same issue in Firefox (39.0 on mac).
If helps here is a codeplan: http://codepen.io/eloyleonardo/pen/QbZvwG

How to proceed: 
* You need to make a scroll (just see some itens never see all).
* Go to the first item and select a state.
* Scroll to the last item and select a state. -> when you select you probably will be send to the first item.

**Comment by Splaktar** [comment]
OK that is very helpful. Thank you.

**Comment by robertmesserle** [comment]
This is fixed in master as well as 0.10.1-rc3 - will be in the 0.10.1 release.

**Comment by eloyleonardo** [comment]
Great, thanks

**Comment by Splaktar** [comment]
Yep, the CodePen works great for me in 0.10.1-rc3 on Firefox 39 (OS X).

**Comment by Patrik-Lundqvist** [comment]
Still having this problem in 0.10.1 and current master when using IE 11

See codepen (0.10.1)
http://codepen.io/anon/pen/qdGGYN
