### ISSUE TITLE
mdSelect: selection broken with Angular 1.4.x

### ISSUE THREAD

**Issue by Tyrannmisu** [angular/material#3780]
It is not possible to select an item in the md-select dropdown in FireFox (31 & 40) or Chrome with the 0.10.1-rc2 release (or master) using Angular 1.4.3.

This happens even in the official demo-page :) , the dropdown opens but you can't click anything and are left with the dropdown without the possibility to close it.

**Comment by xenit-raven** [comment]
Also broken in IE. This is a blocking issue when using either md-menu or md-select.

**Comment by hodeyp** [comment]
+1

**Comment by hodeyp** [comment]
This is something to do with the waitTransitionEnd promise. it was fixed in Chrome by adding the finally call as per issue #3704 - if you change the timeout to be a resolve instead of a reject everything works correctly. Assuming there is another place on the open of a select that is waiting indefinitely for a resolve.

**Comment by ThomasBurleson** [comment]
To reproduce:

* Select **State** menu in http://localhost:8080/#/demo/material.components.select Basic Usage<br/> - shows the select dropdown menu
* Click outside in backdrop area (off the select menu)
* Select again the State menu to show the dropdown menu
* Can no longer close the menu, clicks on the backdrop area no longer close the menu.

> Note: mdSelect uses nested $$rAF calls.

**Comment by Tyrannmisu** [comment]
Seems to work fine now, thanks ! :)

**Comment by stefan-schweiger** [comment]
@robertmesserle `md-menu` is still broken in IE (IE11 + Win8) on the [demo page](https://material.angularjs.org/HEAD/#/demo/material.components.menu)

https://github.com/angular/material/issues/3837

**Comment by dholcombe** [comment]
I can confirm md-menu is also broken on the HEAD demo page in IE11 + Win7
