### ISSUE TITLE
When page is scrolled, bottom sheet is positioned incorrectly

### ISSUE THREAD

**Issue by okelepko** [angular/material#4801]
I believe, #1426 hasn't been resolved.
Scroll down and click the button: http://jsfiddle.net/xejh7mrd/

![image](https://cloud.githubusercontent.com/assets/9936120/10052715/20e43d2e-61dd-11e5-965c-99f8c528c6a3.png)

**Comment by fabio-vitali** [comment]
+1

**Comment by animesh1987** [comment]
+1

**Comment by fabio-vitali** [comment]
I fixed it setting the position of the bottomsheet and the backdrop to "fixed"

**Comment by albertosantini** [comment]
i don't know if it is related but it is also added a scrollbar to the page.

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by okelepko** [comment]
http://codepen.io/anon/pen/XmeoXE

![image](https://cloud.githubusercontent.com/assets/9936120/10523430/4ca135da-732f-11e5-97ab-d83bd4357cfe.png)

**Comment by amritk** [comment]
@ThomasBurleson can confirm that this is definitely still broken.

Angular 1.5.3
Angular Material 1.0.7

http://codepen.io/anon/pen/MyEOVW

**Comment by p-mcgowan** [comment]
confirmed - does not work on Angular 1.0.7 and Material 1.1.0-rc2

**Comment by p-mcgowan** [comment]
also broken in 
  angular-material 1.1.0-rc4,
  angular 1.5.5

manually setting `.md-bottom-sheet { position:fixed; }` is a workaround for the time being, as `position: absolute` appears to be the problem

**Comment by stephengardner** [comment]
+1,
Not a fan of workarounds :/
