### ISSUE TITLE
md-authcomplete make the not-found item clickable

### ISSUE THREAD

**Issue by ido567** [angular/material#4855]
There is a way to make the md-not-found item clickable?
I tried to put an ng-click on the md-not-found, or to wrap the content with div with ng-click (which worked on 0.10.0) but I doesn't work on 0.11.1
```html
<md-autocomplete
	md-search-text="searchText"
	md-items="channel in search(searchText)"
	md-delay="100"
	md-min-length="1"
	md-selected-item-change="goToChannel(channel)"
	placeholder="Search for an artist">

	<md-item-template>
		<span md-highlight-text="searchText" md-highlight-flags="^i">{{ channel.name }}</span>
		<span style="float: right">{{ channel.subscriptions }} Subscribers</span>
	</md-item-template>

	<md-not-found>
		<div ng-click="goToCreateChannel(searchText)">
			No matches found for "{{ searchText }}".
			Find {{ searchText }} on the web!
		</div>
	</md-not-found>
</md-autocomplete>
```

**Comment by topherfangio** [comment]
Can you please provide a Codepen using 11.1 which demonstrates this so that we can investigate further?

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.6 (or greater).

**Comment by ido567** [comment]
Ok, I tried to add to your example an console.log when the 'no-items-found' item is clicked.
Let me know if you need something else
https://codepen.io/anon/pen/GpNbpW

**Comment by topherfangio** [comment]
Okay, thanks. I think the mousedown event is getting trapped by the autocomplete somewhere and preventing the default.

For reference, though, you can't call arbitrary JS code using `ng-click`. It must be a function on the controller/scope (I updated the codepen, but it still didn't work).

**Comment by ido567** [comment]
Do you know when 0.12.0 is scheduled to be published?

**Comment by paulflo150** [comment]
I looked at this several weeks ago since I use this functionality quite often, and as I recall the problem is the blur that fires when you click on the not-found template, which subsequently hides the template, so your click event gets lost.

Not the most elegant solution, but until the angular material team gets this fixed you could try extending the autocomplete functionality yourself:

https://github.com/paulflo150/paulflo150.github.io/commit/0403f0e569507e45a66fe7d2b405a1fb90249fbb

And to use it:

````
<md-autocomplete 
               ...
               md-not-found-click="add($event, query)"
               ...
               <md-item-template>
                         <span md-highlight-text="query" md-highlight-flags="ig" class="item-title">
                                  {{ operator.CompanyName }}
                          </span>
               </md-item-template>
               <md-not-found>
                           Click to <strong>add</strong>
               </md-not-found>
</md-autocomplete>
````

**Comment by ido567** [comment]
Great! When it is scheduled to be published?

**Comment by topherfangio** [comment]
@ido567 It is available in master right now. Can you take a look and make sure it works for you? I updated the [first autocomplete demo](https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete) to show an example usage. Just type a non-state in the box to see the `md-not-found` message and click the "Create a new one!" link.

**Comment by ido567** [comment]
Looks good! 
I think it's necessary to close the auto completion after the click, or to give us the abillity to close it programmatically

**Comment by ido567** [comment]
Hi again, 
What's about closing the suggestions programatically?
Or to close it after the inner link of the md-not-found is clicked?

**Comment by topherfangio** [comment]
@ido567 That's a great point, can you open a second issue for that?

Also, as a temporary workaround, you could programatically set `md-min-length` to a really high value so that it doesn't show suggestions.

**Comment by ido567** [comment]
Done!

**Comment by andrewmcconville** [comment]
@topherfangio I'm on the demo page for autocomplete and the "Create a new one!" link is not working, nor does it work in my implementation which is a copy and paste of the demo code.

It looks like the same problem still exists where clicking the "Create a new one!" link blurs the md-autocomplete input. The md-not-found container just goes empty on mouse down.

**Comment by topherfangio** [comment]
@andrewmcconville Indeed; it looks like a regression. Can you open a new issue with your info/code, reference this one and ping me please?
