### ISSUE TITLE
md-datepicker in demo site comes up as translucent

### ISSUE THREAD

**Issue by gkohen** [angular/material#5187]
On the Angular Material website demo md-datepicker material comes up with a transparent background:
https://material.angularjs.org/latest/demo/datepicker
See screenshot:
http://www.webpagescreenshot.info/img/561fd27f5e1fc6-88954217

**Comment by alexhawkins** [comment]
yeah, having this problem as well. You can add your own css to temporarily fix but It looks like it's been fixed in HEAD.

**Comment by colinskow** [comment]
+1

**Comment by spookmx** [comment]
+1

**Comment by gkohen** [comment]
This is a duplicate of https://github.com/angular/material/issues/5116

**Comment by cindyfallasv** [comment]
This is still happening on version 0.11.4 https://material.angularjs.org/latest/demo/datepicker

**Comment by spookmx** [comment]
Not on 0.11.3, and since it is fixed on head I would assume that 0.11.5 will be ok.

https://material.angularjs.org/0.11.3/demo/datepicker

**Comment by gkohen** [comment]
Have a look at 0.12.0-rc1. release? This bug fix seemed to have solved the
issue: https://github.com/angular/material/issues/5141

**Comment by gkohen** [comment]
Heads up. The new release name was changed to 1.0.0-rc1.
