### ISSUE TITLE
<md-datepicker> : 5 Bugs as a summary

### ISSUE THREAD

**Issue by bastienJS** [angular/material#5349]
I use angular-material-design v1.0.0-rc1.
I use google chrome Version 46.0.2490.80 m on Windows 10 64-bit
My codepen live example: http://codepen.io/helloworld/pen/NGYxKo
Related Issues - has a similar issue been reported before? YES, but nobody answers those issue.

Have a look at those images or check the codepen above:

![image](https://cloud.githubusercontent.com/assets/5945955/10712660/ad158024-7aa0-11e5-943a-54fa9701b7d9.png)

![image](https://cloud.githubusercontent.com/assets/5945955/10712670/5bcb89ec-7aa1-11e5-907d-b5fa8ce9e72b.png)

![image](https://cloud.githubusercontent.com/assets/5945955/10712769/ac5cbf0a-7aa3-11e5-83f4-47ae4bc2eaf7.png)

Here are **FIVE** bugs on the latest version

- White background?
- Not aligned to other controls
- Triangle/arrow should have black color
- Transparent background above/below the data string
- When no date is selected the ng-messages are broken...

Thanks for making your md-datepicker consistent with your other controls.

**Comment by RolandHeath** [comment]
For theming your background colour, you should use md-content and [$mdThemingProvider](https://material.angularjs.org/latest/Theming/03_configuring_a_theme), as shown in this [modified version](http://codepen.io/anon/pen/RWMZpJ?editors=101) of your codepen. This should ensure that background themes are applied properly on angular material elements. 

However, this only fixes some of the above issues.

**Comment by jelbourn** [comment]
@bastienJS For the future, please file separate issues. It's hard to manage when a bunch of reports are thrown into one issue, since we can't mark duplicates or close things that are already fixed.

**Comment by ThomasBurleson** [comment]
@jelbourn - should we ask @bastienJS  to make separate issues?

**Comment by jelbourn** [comment]
Don't worry about it for this one.

**Comment by bastienJS** [comment]
The RC3 or RC4 did not fix anything. Just the opposite. Everything is the same buggy + one new label position bug. I have decided today to stop using angular material and go with angular ui bootstrap as they offer a way more stable release candidate also concerning in combination with ui router.

http://codepen.io/anon/pen/OydPQL (RC4)

**Comment by momo898821** [comment]
Not aligned to other controls.+1.
It seems like that the <md-datepicker> doesn't work very friendly with other form controls(like input,md-select).Other form controls are in a container(<md-input-container>),but Datepicker doesn't have one.I think that may be the reason why it not aligned to other controls.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
