### ISSUE TITLE
md-list-item's with ng-href vs ng-click - styling differences

### ISSUE THREAD

**Issue by cgross** [angular/material#5909]
Right now, you can only create a clickable list item via ng-click.  Would like the same ability but using ng-href thus making the item a hyperlink (which allows open-in-new-tab behavior).

**Comment by gpopovic** [comment]
This is already working?
Are you sure you're using ng-href correctly?

**Comment by cgross** [comment]
I'm using 0.11.4 and it doesn't appear to work to me:

```html
<md-list-item ng-href="/whatever">blah</md-list-item>
````

**Comment by cgross** [comment]
Just checked in rc4 and it does appear to be working now.  But there's styling differences between the two.  With ng-href, the item has extra padding and the font weight is heavier.

**Comment by angrybakon** [comment]
@cgross I too was looking for the same thing. Turns out I'm better off using code from master :).

It appears that to make the links work, they create `<a>` elements underneath styled with `.md-button` which in turn add margins and a different font weight. This is easily fixed with custom CSS but drastically uglify the code.

**Comment by timediv** [comment]
What's the status on this?

**Comment by matt-neill** [comment]
+1

**Comment by JasonTheProgrammer** [comment]
To repeat timediv, what's the status on this? I've gone down the rabbit-hole of related issues as far as I can find... #6317, #6496, #6507. All, along with this one, are status "closed". But the issue persists. [Here's a pen showing it in 1.0.9](http://codepen.io/JasonTheProgrammer/pen/beGMab), note that the 'Hello' and 'World' button/link are styled differently.

**Comment by jbcpollak** [comment]
this styling bug is still present as of now... I'm not sure why it is closed.

**Comment by Carozonator** [comment]
I was using ui-sref and there is a weird bug that will click thru in the next view after states changed). fixed using ng-click.

**Comment by JasonTheProgrammer** [comment]
[Updated pen showing it working as expected in 1.1.1](http://codepen.io/JasonTheProgrammer/pen/RKdPQK).
