### ISSUE TITLE
md-bottom-sheet animation is broken

### ISSUE THREAD

**Issue by yxh10** [angular/material#6692]
When triggering bottom sheet, the slide up animation is broken. The bottom sheet appears instantly. There is no transition animation. But slide out (hide) animation works just fine. This happens in both 1.0.1 and 1.0.2. 

To observe this, simply make the bottom sheet take 100% screen size, then it become obvious. 

Thanks!

**Comment by 0101adm** [comment]
this is a dup and i believe there is already a fix.

**Comment by DevVersion** [comment]
Yes, that's a dupe of  #6468 and is solved in #6484

**Comment by ThomasBurleson** [comment]
Duplicate

**Comment by aidarbuy** [comment]
The slide up animation is still broken in 1.0.5

**Comment by Kasahs** [comment]
The slide up animation is still broken in 1.0.8 is there any branch or commit I can use to fix this temporarily?

**Comment by trstowell** [comment]
+1, my slide-up animation becomes intermittently broken. With no styling changes it will work for weeks on end, then suddenly break, then work again some time later.

![bottomsheet](https://user-images.githubusercontent.com/3466736/28585190-7abf7eb4-713d-11e7-8e14-b4eaaf04e544.gif)
