### ISSUE TITLE
required on md-select adds md-input-invalid even if select has a value selected

### ISSUE THREAD

**Issue by lexyfeito** [angular/material#9030]
Here is the plunker https://plnkr.co/edit/nP19I1zWBu6rb9Cf56Sv?p=preview

Notice how the first select input would show red even if it has a value selected.

**Comment by DevVersion** [comment]
Fixed within `master`

**Comment by lexyfeito** [comment]
@DevVersion Should i pull master of do you know when the fix will be released?

**Comment by DevVersion** [comment]
@lexyfeito For now you could use `v1.1.0-rc.5`. The major release for `v1.1.0` is planned soon.

**Comment by lexyfeito** [comment]
@DevVersion awesome thank you

**Comment by ashishpatel02** [comment]
@DevVersion , I'm Using 1.1.0 Of Angular and Still Facing Same issues. Please help!

**Comment by ashishpatel02** [comment]
The Issues Is Faced By Few More user Now. Referred [Link](https://github.com/angular/material/issues/10264 )

**Comment by ashishpatel02** [comment]
@DevVersion  Weird Thing Is When I Check With this.$scope.formName.$invalid, Shows Me False Then Also I'm Getting Required.
